# Generated by Django 6.1.1 on 2026-09-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='We shape the way a brand is *seen*, frame by frame.', help_text='Wrap one word or phrase in *asterisks* to set it in the orange italic.', max_length=200)),
                ('description', models.TextField(default='Media Nest is a brand image management and consultancy practice. We create and curate visual content that drives engagement, trust and lasting presence — from photography and cinematography through to strategy, events and digital.', help_text='The paragraph to the right of the heading.')),
                ('figure', models.ImageField(blank=True, help_text='The large image beside the pillars. The frame is 433x458 on a desktop and crops to fill, so upload at least 866x916 to stay sharp on a 2x screen.', upload_to='about/')),
                ('figure_alt', models.CharField(default='A Media Nest studio set lit for an interview shoot', help_text='Described for screen readers and shown if the image fails to load.', max_length=200)),
                ('focal_x', models.PositiveSmallIntegerField(default=50, help_text='Horizontal focus, 0-100. Move it when the crop cuts the subject.')),
                ('focal_y', models.PositiveSmallIntegerField(default=50, help_text='Vertical focus, 0-100.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'about content',
                'verbose_name_plural': 'about content',
            },
        ),
        migrations.CreateModel(
            name='AboutPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('is_wide', models.BooleanField(default=False, help_text='Spans 8 columns instead of 4. Exactly one pillar should have this.')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'about pillar',
                'verbose_name_plural': 'about pillars',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='Visual Excellence, Tangible Results', help_text='Appears in the nav and on the About figure.', max_length=120)),
                ('years_of_practice', models.CharField(default='5+', help_text='As displayed, including the plus: "5+". Shown in the hero, About and Why Choose Us.', max_length=12)),
                ('discipline_count', models.CharField(default='9', help_text='The digit form: "9". Used in the About stats row.', max_length=12)),
                ('discipline_count_word', models.CharField(default='Nine', help_text='The word form: "Nine". The hero writes "Nine disciplines".', max_length=24)),
                ('hours_compact', models.CharField(default='24/7', help_text='Tight form for the stats row: "24/7".', max_length=16)),
                ('hours_spaced', models.CharField(default='24 x 7', help_text='Spaced form used in prose and the footer: "24 x 7".', max_length=16)),
                ('coverage', models.CharField(default='Global', help_text='Where the firm works: "Global".', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
