# Generated by Django 6.1.1 on 2026-09-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The full name on the card, e.g. "Photography & Brand Visual Presence".', max_length=120)),
                ('short_label', models.CharField(blank=True, help_text='The short name in the left-hand rail, e.g. "Photography". Falls back to the title.', max_length=60)),
                ('body', models.TextField(blank=True, help_text='Shown under the name in the rail. Featured services only.')),
                ('tags', models.CharField(blank=True, help_text='Comma separated, e.g. "Editorial, Product, Sports, Profiling". Featured services only.', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='The card image. The frame is 457x610 and crops to fill, so upload at least 914x1220 to stay sharp on a 2x screen.', upload_to='services/')),
                ('focal_x', models.PositiveSmallIntegerField(default=50, help_text='Horizontal focus, 0-100.')),
                ('focal_y', models.PositiveSmallIntegerField(default=50, help_text='Vertical focus, 0-100.')),
                ('is_featured', models.BooleanField(default=False, help_text='On: a full card with image, body and tags. Off: name only, in the strip below.')),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
