# Generated by Django 6.1.1 on 2026-09-23 11:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The tile label, e.g. "Photography".', max_length=80)),
                ('meta_label', models.CharField(blank=True, help_text='The small word above the name, e.g. "Stills", "Motion", "Broadcast".', max_length=40)),
                ('cover', models.ImageField(blank=True, help_text='The tile image. How large it needs to be depends on which slot it lands in.', upload_to='disciplines/')),
                ('focal_x', models.PositiveSmallIntegerField(default=50, help_text='Horizontal focus, 0-100.')),
                ('focal_y', models.PositiveSmallIntegerField(default=50, help_text='Vertical focus, 0-100.')),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='disciplines/gallery/')),
                ('alt', models.CharField(help_text='Required — it is read out to screen readers and shown if the image fails.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.discipline')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(help_text='The 11-character id from the URL: youtube.com/watch?v=<this>', max_length=20, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_-]{11}$', 'A YouTube id is exactly 11 characters. Paste the id, not the whole URL.')])),
                ('title', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content.discipline')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
