# Generated by Django 6.1.1 on 2026-09-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_discipline_disciplineimage_disciplinevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Set at display size, and it has to stay on one line — 25 characters is what fits.', max_length=25)),
                ('body', models.TextField(help_text='Up to 170 characters. Past that the copy pushes the rule below it and the section shifts as you scroll.', max_length=170)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='{count} reasons brands *stay*.', help_text='Use {count} where the number of reasons should go — it is written out as a word (Four, Five) and updates itself when reasons are added or removed. Put *asterisks* around the one accented word.', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'why choose heading',
                'verbose_name_plural': 'why choose heading',
            },
        ),
    ]
