# Generated by Django 6.1.1 on 2026-09-24 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_reason_whychoosecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='body',
            field=models.TextField(help_text='Up to 170 characters. Past that the copy pushes the rule below it and the section shifts as you scroll.', max_length=170, validators=[django.core.validators.MaxLengthValidator(170)]),
        ),
    ]
