# Generated by Django 6.1.1 on 2026-09-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_reason_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ['order', 'id'], 'verbose_name': 'projects_selected_work', 'verbose_name_plural': 'projects_selected_work'},
        ),
        migrations.AlterModelOptions(
            name='disciplineimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'still', 'verbose_name_plural': 'stills'},
        ),
        migrations.AlterModelOptions(
            name='disciplinevideo',
            options={'ordering': ['order', 'id'], 'verbose_name': 'film', 'verbose_name_plural': 'films'},
        ),
        migrations.AlterModelOptions(
            name='reason',
            options={'ordering': ['order', 'id'], 'verbose_name': 'projects_why_choose_us', 'verbose_name_plural': 'projects_why_choose_us'},
        ),
        migrations.AlterModelOptions(
            name='whychoosecontent',
            options={'verbose_name': 'projects_why_choose_us_heading', 'verbose_name_plural': 'projects_why_choose_us_heading'},
        ),
    ]
