# Generated by Django 6.1.1 on 2026-09-24 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_discipline_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Set in roman, e.g. “Aditi”.', max_length=40)),
                ('last_name', models.CharField(help_text='Set in the orange italic beneath the given name, e.g. “Singh”.', max_length=40)),
                ('role', models.CharField(help_text='e.g. "Managing Partner".', max_length=60)),
                ('photo', models.ImageField(blank=True, help_text='Portrait, cropped to 3:4. Upload at least 920x1226 so it stays sharp on a phone or a retina screen.', upload_to='team/')),
                ('focal_x', models.PositiveSmallIntegerField(default=50, help_text='Horizontal focus, 0-100.')),
                ('focal_y', models.PositiveSmallIntegerField(default=50, help_text='Vertical focus, 0-100.')),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'team_the_partners',
                'verbose_name_plural': 'team_the_partners',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='{count} photographers running a *practice*.', help_text='Use {count} where the number of people should go — it is written out as a word (Two, Three) and updates itself. Put *asterisks* around the one accented word.', max_length=140)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'team_the_partners_heading',
                'verbose_name_plural': 'team_the_partners_heading',
            },
        ),
        migrations.CreateModel(
            name='PersonLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='e.g. "Still Life & Sports Photographer".', max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='content.person')),
            ],
            options={
                'verbose_name': 'line',
                'verbose_name_plural': 'lines',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PersonSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('url', models.URLField(help_text='The full link to the profile.', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='content.person')),
            ],
            options={
                'verbose_name': 'social link',
                'verbose_name_plural': 'social links',
                'ordering': ['order', 'id'],
            },
        ),
    ]
