# Generated by Django 6.1.1 on 2026-09-24 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_person_teamcontent_personline_personsocial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(help_text="Up to 260 characters. The carousel's box is sized for exactly this, so that paging between quotes moves nothing on the page.", max_length=260, validators=[django.core.validators.MaxLengthValidator(260)])),
                ('name', models.CharField(max_length=80)),
                ('role', models.CharField(help_text='Their title and organisation, e.g. "President, Pan American Billiards & Snooker Association".', max_length=120)),
                ('photo', models.ImageField(blank=True, help_text='Shown as a 62px circle, so upload at least 124x124. A square crops best.', upload_to='testimonials/')),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'team_in_their_words',
                'verbose_name_plural': 'team_in_their_words',
                'ordering': ['order', 'id'],
            },
        ),
    ]
