# Generated by Django 6.1.1 on 2026-09-24 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='As printed on the card, e.g. "Indian Oil".', max_length=60)),
                ('sector', models.CharField(help_text='What the organisation is, not a claim about the work — "International Federation", "Energy".', max_length=60)),
                ('logo', models.ImageField(blank=True, help_text='Shown at up to 76x68 and never cropped, so upload at least 152x136. Transparent or white background.', upload_to='clients/')),
                ('url', models.URLField(blank=True, help_text='Optional. With a link the card opens it in a new tab and shows the arrow badge; without one it is still shown, just not clickable.', max_length=300, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'clients_trusted_by',
                'verbose_name_plural': 'clients_trusted_by',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClientsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Federations, institutions and *enterprises*.', help_text='Wrap one word or phrase in *asterisks* to set it in the orange italic.', max_length=160)),
                ('note', models.TextField(default='The organisations we produce for, across sport, energy and public enterprise. Together we create stories that move people and build lasting impact.', help_text='The paragraph to the right of the heading.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'clients_trusted_by_heading',
                'verbose_name_plural': 'clients_trusted_by_heading',
            },
        ),
    ]
