# Generated by Django 6.1.1 on 2026-09-24 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_client_clientscontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Let us make your brand look *inevitable*.', help_text='Wrap one word or phrase in *asterisks* to set it in the orange italic.', max_length=160)),
                ('lede', models.TextField(default='Tell us what you are building. We reply within one working day — every day, {hours}.', help_text='Use {hours} where the working hours should go — it is filled from Site settings so this cannot disagree with the rest of the page.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'contact_start_a_project',
                'verbose_name_plural': 'contact_start_a_project',
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='connect@medianest.co.in', help_text='Shown and linked in the contact panel, the footer and the mobile menu.', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='firm_name',
            field=models.CharField(default='Media Nest', help_text='The legal or trading name, as the contact panel prints it.', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_display',
            field=models.CharField(default='+91-8448112770', help_text='As it should read on the page, punctuation and all: "+91-8448112770".', max_length=32),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_e164',
            field=models.CharField(default='+918448112770', help_text='The dialable form. Both the tap-to-call link and the WhatsApp link are built from this, so it has to be the bare international number.', max_length=20, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{7,14}$', 'Write it as a plus, the country code and the number, with no spaces or dashes: +918448112770.')]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_message',
            field=models.CharField(default='Hi, I visited your website and want to know more.', help_text='Pre-filled in the WhatsApp chat the footer icon opens.', max_length=200),
        ),
    ]
