# Generated by Django 6.1.1 on 2026-09-24 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_contactcontent_sitesettings_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blurb', models.TextField(default='Brand Image Management & Consultancy. Creating and curating impactful visual content that amplifies brand presence and identity.', help_text='The paragraph under the logo.')),
                ('legal_note', models.CharField(default='All rights reserved.', help_text="Follows the year and the firm's name on the bottom line. The “© 2026 Media Nest.” part is built from the clock and Site settings, so it cannot go stale.", max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'footer',
                'verbose_name_plural': 'footer',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp')], max_length=20, unique=True)),
                ('url', models.URLField(blank=True, help_text='Leave blank for WhatsApp — that link is built from the phone number.', max_length=300, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'footer_social_link',
                'verbose_name_plural': 'footer_social_links',
                'ordering': ['order', 'id'],
            },
        ),
    ]
