# Generated by Django 6.1.1 on 2026-09-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_footercontent_sociallink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['order', 'id'], 'verbose_name': 'social link', 'verbose_name_plural': 'social links'},
        ),
    ]
