# Generated by Django 6.1.1 on 2026-09-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_sociallink_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'publish state',
                'verbose_name_plural': 'publish state',
            },
        ),
    ]
