# Generated by Django 6.1.1 on 2026-09-25 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_publishstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_url',
            field=models.URLField(blank=True, help_text='Optional. Set it and the footer shows a small “Admin” link; leave it blank and there is no link at all. Putting one on the public site makes the admin address public too, so only set this once the password is a strong one.', max_length=300, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
